### ISSUE TITLE
SON form interactions

### ISSUE THREAD

**Issue by woodseowl** [CU-CommunityApps/cd-son#11]
As a form submitter, I want be sure that the NetID I use for "submitted for someone else" is valid and I want to know the next steps.

Requirements
 - [x] User types in NetID (not email)
 - [x] Validation looks up NetID in directory to confirm it exists (and is active?)
 - [x] Web frontend conditional text displays when checked
 - [x] Cloud-based conditional text displays when checked

**Comment by philwilliammee** [comment]
11 son form interactions #22 ciompletes this in minimum. But I want to make a slick serch select that is WA.
