### ISSUE TITLE
Submitting for someone else clarifications

### ISSUE THREAD

**Issue by woodseowl** [CU-CommunityApps/cd-son#27]
The "submitting for someone else" scenario should be clarified.

- Do we consider the person it is submitted for to be the one who should show up in list and detail views as the primary person?

I thought there were other questions, but maybe that is all we need to answer and then we make interface changes if needed.

**Comment by philwilliammee** [comment]
Discussed in the meeting the submitter should be the person filling out the form. The person submitting for someone else can be cc’ed.

**Comment by woodseowl** [comment]
Great, the form presents this way, so I'm going to close this. Thanks for documenting, Phil!
