### ISSUE TITLE
Current list of approved SONs

### ISSUE THREAD

**Issue by philwilliammee** [CU-CommunityApps/cd-son#45]
As an authorized member of IT governance, I want to see the list of approved SONs.

Requirements
- [x] "Front end" style view of SONs list at /current-sons
- [x] Basic list view for sons at /sons
- [x] Sons list view removed from /home
- [x] "Statements of Need" link to /sons in Contributor Links menus
- [x] /home -> /dashboard + "Dashboard" link added to main navigation
- [x] I can search for SONs
- [x] A nicely formatted list view of statements of need (https://it.cornell.edu/itgovernance-project-management/3-current-it-statements-need-and-it-project-charters-access)

**Comment by woodseowl** [comment]
Perhaps this is the story...

As an authorized member of IT governance, I want to see the list of approved SONs.

Requirements
- [ ] "Front end" style view of SONs list at /current-sons
- [ ] Basic list view for sons at /sons
- [ ] Sons list view removed from /home
- [ ] "Statements of Need" link to /sons in Contributor Links menus
- [ ] /home -> /dashboard + "Dashboard" link added to main navigation
