### ISSUE TITLE
Refactor netid validation code

### ISSUE THREAD

**Issue by philwilliammee** [CU-CommunityApps/cd-son#54]
I was a little confused by this code. See what you think of this...

```
        if (empty($netid)) {
            return;
        }

        // If LDAP server gives an error just submit the form.
        try {
            $data = LDAP::data($netid);
        } catch (Exception $e) {
            Log::error($e->getMessage());
            return;
        }
        
        if (empty($data)) {
            throw ValidationException::withMessages(['submiting_for_netid' => 'Invalid netid']);
        }
```

I think that was what you meant in the comment. Not positive.

_Originally posted by @woodseowl in https://github.com/CU-CommunityApps/cd-son/pull/49_

**Comment by woodseowl** [comment]
Note that testing this should include creating a new SoN without a SubmittedForNetID value. I just tested on #49 and that is failing in the current code.
