### ISSUE TITLE
Use "Not Approved" instead of "Abandoned"

### ISSUE THREAD

**Issue by philwilliammee** [CU-CommunityApps/cd-son#55]
Naming... I think we should settle on making everything that had been called "abandoned" be "not approved". There is language for both in the code right now.

_Originally posted by @woodseowl in https://github.com/CU-CommunityApps/cd-son/pull/49_

**Comment by woodseowl** [comment]
I looked at some notes from our meeting with Shanon and see that we had language for "approved / declined / abandoned". I am now uncertain about the workflow and messaging language. I think we need to get this clarified before proceeding.

**Comment by woodseowl** [comment]
Alright, discussed in Slack and should be good with "not approved" as the workflow state.

**Comment by philwilliammee** [comment]
@woodseowl abandoned name/value will be changed to not_approved label will be "Not Approved"
