### ISSUE TITLE
Basic login

### ISSUE THREAD

**Issue by woodseowl** [CU-CommunityApps/cd-son#7]
As a user I can see a Welcome page and login to see the Home page.

Requirements
 - [x] Welcome page has introductory text
 - [x] There is a link to SAML login
 - [x] When I log in successfully I go to the Home page
 - [x] Home page displays the logged in user's ID

**Comment by philwilliammee** [comment]
commit c2696f5 implements this feature

**Comment by philwilliammee** [comment]
merge 7 basic login #24 closes this
